name: RAISING

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      # Step 3: Install dependencies and build the package
      - name: Build release distributions
        run: |
          python -m pip install --upgrade pip setuptools wheel twine build
          python -m build

      # Step 4: Validate metadata before publishing
      - name: Validate metadata
        run: |
          python -m pip install twine
          twine check dist/*

      # Step 5: Upload built artifacts
      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      id-token: write

    environment:
      name: pypi
      # OPTIONAL: Add PyPI project URL for deployment status tracking
      # url: https://pypi.org/project/YOURPROJECT/

    steps:
      # Step 1: Retrieve the built artifacts
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      # Step 2: Publish to PyPI
      - name: RAISING
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
